export const APPOINTMENT_UPLOAD = 'APPOINTMENT_UPLOAD'
export const APPOINTMENT_MAKE = 'APPOINTMENT_CREATE'

export const APPOINTMENT_UPLOAD_SUCCESS = 'APPOINTMENT_UPLOAD'
export const APPOINTMENT_MAKE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS'

export const APPOINTMENT_UPLOAD_ERROR = 'APPOINTMENT_UPLOAD'
export const APPOINTMENT_MAKE_ERROR = 'APPOINTMENT_CREATE_ERROR'
