export const MASTER_UPLOAD = 'MASTER_UPLOAD'
export const MASTER_SUPPLEMENT = 'MASTER_SUPLEMENT'

export const MASTER_UPLOAD_SUCCESS = 'MASTER_UPLOAD_SUCCESS'
export const MASTER_SUPPLEMENT_SUCCESS = 'MASTER_SUPLEMENT_SUCCESS'

export const MASTER_UPLOAD_ERROR = 'MASTER_UPLOAD_ERROR'
export const MASTER_SUPPLEMENT_ERROR = 'MASTER_SUPLEMENT'
