export const PROFILE_UPLOAD = 'PROFILE_UPLOAD'
export const PROFILE_UPLOAD_SERVICES = 'PROFILE_UPLOAD_SERVICES'

export const PROFILE_UPLOAD_SUCCESS = 'PROFILE_UPLOAD_SUCCESS'
export const PROFILE_UPLOAD_SERVICES_SUCCESS = 'PROFILE_UPLOAD_SERVICES_SUCCESS'

export const PROFILE_UPLOAD_ERROR = 'PROFILE_UPLOAD_ERROR'
export const PROFILE_UPLOAD_SERVICES_ERROR = 'PROFILE_UPLOAD_SERVICES_ERROR'

