export const SERVICE_UPLOAD = 'SERVICE_UPLOAD'
export const SERVICE_FIND = 'SERVICE_FIND'

export const SERVICE_UPLOAD_SUCCESS = 'SERVICE_UPLOAD_SUCCESS'
export const SERVICE_FIND_SUCCESS = 'SERVICE_FIND_SUCCESS'

export const SERVICE_UPLOAD_ERROR = 'SERVICE_UPLOAD_ERROR'
export const SERVICE_FIND_ERROR = 'SERVICE_FIND_ERROR'
