export const USER_UPLOAD = 'USER_UPLOAD'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_BECOME_CLIENT = 'USER_BECOME_CLIENT'
export const USER_BECOME_MASTER = 'USER_BECOME_MASTER'

export const USER_UPLOAD_SUCCESS = 'USER_UPLOAD_SUCCESS'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_BECOME_CLIENT_SUCCESS = 'USER_BECOME_CLIENT_SUCCESS'
export const USER_BECOME_MASTER_SUCCESS = 'USER_BECOME_MASTER_SUCCESS'

export const USER_UPLOAD_ERROR = 'USER_UPLOAD_ERROR'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'
export const USER_BECOME_CLIENT_ERROR = 'USER_BECOME_CLIENT_ERROR'
export const USER_BECOME_MASTER_ERROR = 'USER_BECOME_MASTER_ERROR'
