export const USER_UPLOAD = 'USER_UPLOAD'
export const USER_UPDATE = 'USER_UPDATE'

export const USER_UPLOAD_SUCCESS = 'USER_UPLOAD_SUCCESS'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'

export const USER_UPLOAD_ERROR = 'USER_UPLOAD_ERROR'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'
